'''
Even Fibonacci Numbers

Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1,2,3,5,8,13,21,34,55,89

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Ans:
4613732
'''

def fibonacci():
    seq = [1,2]
    
    while True:
        next = sum(seq[-2:])
        if next < 4_000_000:
            seq.append(next)
        else:
            break
        
    return seq

def is_even(num):
    return num % 2 == 0

def main():
    seq = fibonacci()
    print(seq)
    
    total = 0
    for i in seq:
        if is_even(i):
            total += i

    print(total)
    
if __name__ == "__main__":
        
    main()